language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install coverage coveralls
script:
    - coverage run --source=gnarl setup.py test -v
    - coverage report -m
after_success: coveralls
