language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install green coverage coveralls hipack
    - pip install -r requirements.txt
script:
    - green -r -v -s 8
after_success: coveralls
